import type { Metadata } from "next";

import HeaderNav from "@/components/layout/header-navigator";
import FooterNav from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="w-full bg-white">
      <HeaderNav />
      {children}
      <FooterNav />
    </main>
  );
}
